version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app" 
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      
